const USERNAME_OR_PASSWORD_IS_REQUIRED = '用户名或密码为空'
const USERNAME_ALREADY_EXIST = '用户名已存在'
const NOT_FOUND = 'NOT FOUND'

module.exports = {
  USERNAME_OR_PASSWORD_IS_REQUIRED,
  USERNAME_ALREADY_EXIST,
  NOT_FOUND,
}
